name: Run Bot Script

on:
  schedule:
    # Exécute le script toutes les heures
    - cron: "0 * * * *"
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install schedule
        pip install kucoin
        pip install requests

    - name: Run script
      run: python bot.py
      
