name: Run Bot Script

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Étape 2 : Télécharger le code source
    - name: Check out code
      uses: actions/checkout@v2

    # Étape 3 : Effacer le cache pip (optionnel, pour éviter les conflits)
    - name: Clear pip cache
      run: pip cache purge

    # Étape 4 : Installer les dépendances depuis requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Étape 5 : Installer kucoin depuis GitHub (si nécessaire)
    - name: Install kucoin from GitHub
      run: pip install git+https://github.com/Kucoin/kucoin-python-sdk.git

    # Étape 6 : Exécuter ton script Python
    - name: Run bot script
      run: python bot_alertes.py
      
