name: Run Bot Script

on:
  workflow_dispatch:  # Permet de déclencher manuellement
  schedule:
    - cron: "0 */3 * * *"  # Exécution toutes les 3 heures

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code
      - name: Check out code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Utilise Python 3.8

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install kucoin

      # Étape 4 : Exécution du script
      - name: Run bot script
        run: python bot_alertes.py
        
