name: Run Bot Script

on:
  workflow_dispatch:  # Permet de déclencher manuellement le workflow
  schedule:
    - cron: "0 */3 * * *"  # Exécute le script toutes les 3 heures

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code
      - name: Check out code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Utilisation de Python 3.9

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: |
          python --version  # Vérification de la version de Python
          pip install --upgrade pip
          pip install kucoin==2.1.2

      # Étape 4 : Exécution du script
      - name: Run bot script
        run: python bot_alertes.py
